environment          = "dev"
team_name            = "team-excellence"
master_instance_type = "t3.small"
worker_instance_type = "t3.small"
worker_count         = 2
volume_size          = 20
vpc_cidr             = "10.20.0.0/16"
public_subnet_cidr   = "10.20.1.0/24"
ssh_allowed_cidr     = "0.0.0.0/0"   # CHANGE THIS — restrict to your IP (e.g. "41.58.x.x/32")