services:
  docs-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthpulse-docs
    ports:
      - "84:80"
    restart: unless-stopped

  docs-dev:
    image: squidfunk/mkdocs-material
    container_name: healthpulse-docs-dev
    ports:
      - "8084:8000"
    volumes:
      - ./mkdocs.yml:/docs/mkdocs.yml:ro
      - ./docs:/docs/docs:ro
    stdin_open: true
    tty: true