site_name: HealthPulse Portal - Team Devius

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Roboto Mono
  logo: images/logo.png
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Environments: environments.md
  - Pipeline: pipeline.md
  - Runbooks: runbooks.md
  - Troubleshooting: troubleshooting.md
  - Contact: contact.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list